apiVersion: v1 # Which predefined object set do we want to utilize
kind: Service # Which type of object do we want to make
metadata:
  name: client-node-port # This is the name of the object - mostly used for logging purposes
spec:
  type: NodePort
  ports: # Describes the different collections of ports that need to be opened up or mapped on the target object (specified by the selector)
    - port: 3050 # Port, that ANOTHER pod could use for accessing this object (the NodePort service)
      targetPort: 3000 # The port of the object (specified by the selector) that we want to open up traffic to
      nodePort: 31515 # The port we are going to access from a Browser in order to test the application hosted by the k8s cluster
  selector:
    component: web # Corresponds to the "web" component in the metadata/labels section of the client-node-port.yaml file
